apiVersion: v1
kind: ReplicationController
metadata:
        name: myrc

spec:
        replicas: 3
        selector:
                dc: IN
        template:
                metadata:
                        name: mypod
                        labels:
                                dc: IN
                spec:
                        containers:
                                - name: myc1
                                  image: httpd
